import { RiDashboardFill } from 'react-icons/ri';
import { BsFillPeopleFill } from 'react-icons/bs';
import { MdInsertComment } from 'react-icons/md';
import { MdOutlineLocalOffer } from "react-icons/md";

export const SidebarContants = [
  {
    link: '/dashboard',
    key: '',
    title: 'Dashboard',
    permissionKey: '',
    tag: null,
    notification: 12,
    IconColor: 'blue',
    icon: <RiDashboardFill />,
    child: [{
      link: '/dashboard',
      key: 'Dashboard',
      title: 'Dashboard',
      permissionKey: '',
      tag: null,
      notification: 12,
      IconColor: 'blue',
      icon: <RiDashboardFill />,
    },
    {
      link: '/dashboard',
      key: 'Dashboard',
      title: 'Dashboard',
      permissionKey: '',
      tag: null,
      notification: 12,
      IconColor: 'blue',
      icon: <RiDashboardFill />,
    }],
  },
  {
    link: '/customer',
    key: '',
    title: 'Offer',
    permissionKey: '',
    tag: 'New',
    notification: null,
    IconColor: 'red;',
    icon: <MdOutlineLocalOffer />,
    child: [],
  },
  {
    link: '',
    key: '',
    title: 'Notification',
    tag: 'Offer',
    permissionKey: '',
    IconColor: 'pink',
    notification: null,
    icon: <MdInsertComment />,
    child: [],
  },
  {
    link: '',
    key: '',
    title: 'Notification',
    tag: 'Offer',
    permissionKey: '',
    IconColor: 'pink',
    notification: null,
    icon: <MdInsertComment />,
    child: [],
  },
  {
    link: '',
    key: '',
    title: 'Notification',
    tag: 'Offer',
    permissionKey: '',
    IconColor: 'pink',
    notification: null,
    icon: <MdInsertComment />,
    child: [],
  },

]